fix: Update tracker docs for Characters not accepted in Tracker capture Attributes [ DHIS2-10215 ]
dhis2/dhis2-docs pull request #1153
Opened 2023-03-14 11:08 UTC by lucaCambi77

see https://github.com/dhis2/dhis2-core/pull/13285

2023-04-04 10:50 UTC, enricocolasante requested changes
Should we change the docs, the code or I am looking at it in the wrong way?

2023-04-04 10:50 UTC, enricocolasante commented on src/developer/web-api/new-tracker.md
> +    GET api/tracker/trackedEntities?orgUnit=DiszpKrYNg8&program=ur1Edk5Oe2n
This request returns a validation error as it seems that filters for attributes are not allowed to be specified more than once.

2023-04-04 11:22 UTC, lucaCambi77 commented on src/developer/web-api/new-tracker.md
> +    GET api/tracker/trackedEntities?orgUnit=DiszpKrYNg8&program=ur1Edk5Oe2n
We have discussed it in the design and also in the PRs like https://github.com/dhis2/dhis2-core/pull/13464. This comes up only now. I didn't remember that. So range for words can't be applied then

2023-04-04 13:24 UTC, enricocolasante commented on src/developer/web-api/new-tracker.md
> +    GET api/tracker/trackedEntities?orgUnit=DiszpKrYNg8&program=ur1Edk5Oe2n
It was unexpected for me as well. I just tried the calls specified in the docs

2023-04-04 13:51 UTC, lucaCambi77 commented on src/developer/web-api/new-tracker.md
> +    GET api/tracker/trackedEntities?orgUnit=DiszpKrYNg8&program=ur1Edk5Oe2n
I didn't check. What we can do is allow multiple filters for the words range in the validation. Otherwise, we need to redefine the split separator or the logic we have in place to manage all cases in the parsing

2023-05-04 12:37 UTC, Philip-Larsen-Donnelly commented
@lucaCambi77 new-tracker.md was recently changed to tracker.md, so the simplest might be to open this again against that file.

2023-06-21 08:00 UTC, closed without merging