feat: linked_accounts in dhis.conf
dhis2/dhis2-docs pull request #1238
Opened 2023-10-06 19:07 UTC by benguaraldi

Documenting a new dhis.conf variable: linked_accounts.enabled introduced with [DHIS2-7093](https://dhis2.atlassian.net/browse/DHIS2-7093)

2023-10-08 21:22 UTC, jimgrace requested changes

2023-10-08 21:22 UTC, jimgrace commented on src/sysadmin/installation.md
> +# Enable a single OIDC accounts to log in as one of several DHIS2 accounts
Change "a single OIDC accounts" to "a single OIDC account". Otherwise looks great!

2023-10-10 18:05 UTC, benguaraldi commented on src/sysadmin/installation.md
> +# Enable a single OIDC accounts to log in as one of several DHIS2 accounts
Thanks, fixed!

2023-10-16 18:33 UTC, jimgrace approved these changes

2023-10-16 18:36 UTC, merged