docs: Add Android blocks with user-agent in nginx
dhis2/dhis2-docs pull request #496
Opened 2020-08-18 08:54 UTC by jaboto

2020-09-28 11:18 UTC, jaboto commented
Hey @Philip-Larsen-Donnelly . Can we get this PR merged?

2020-10-15 13:40 UTC, Philip-Larsen-Donnelly requested changes
This seems to have some git conflict indicator lines surrounding the new text.
Could you remove them please.

2020-10-19 08:55 UTC, jaboto commented
Ahmm, damn! Sorry about that. Fixed now

2020-10-19 11:13 UTC, Philip-Larsen-Donnelly approved these changes

2020-10-19 11:13 UTC, merged