Cause of Death System design document
dhis2/dhis2-docs pull request #515
Opened 2020-09-18 10:56 UTC by enzonr

THis is the System design document for the Cause of Death Package.

And it should essentially be in a similar hierarchical level as the system design doc for COVID.

2020-10-15 14:21 UTC, Philip-Larsen-Donnelly requested changes
Please remove the wrongly placed file and convert the other to markdown.

2020-10-15 14:21 UTC, Philip-Larsen-Donnelly commented on commonmark/en/content/metadata/Cause_of_death.md
> +<!DOCTYPE html>
This is not a markdown file. It is HTML. 
It also seems to be in the wrong place. I presume it should be removed?

2020-10-15 14:21 UTC, Philip-Larsen-Donnelly commented on src/commonmark/en/content/metadata/Cause_of_death.md
> +<!DOCTYPE html>
This file seems to be in the correct place.
But it is not markdown, it is HTML.

Please convert to markdown.

2020-12-15 14:20 UTC, Philip-Larsen-Donnelly requested changes
I have put your pros/cons and stage/descriptions into tables. You should check that they make sense.

2020-12-15 14:20 UTC, Philip-Larsen-Donnelly commented on src/commonmark/en/content/metadata/Cause_of_death.md
> +![](https://lh5.googleusercontent.com/i-BpEnYyZF98nuDvfPjm6tp6L2BEG-LlFwFfo3jLzAkqQ3JlyoK1cJXYO133GB-f3O5sCOJTSar6FHCEtCIUZAnu3hNKxyZwDGOKs3_0rLL839MRAbNP6VomazjyLFROy_PNys_r)
These should be changed to local file references  (resources/images/...)

2020-12-16 13:14 UTC, Philip-Larsen-Donnelly commented
Note that the metadata stuff has also moved to a new repository since you forked this one :grimacing: 
@YuryRog may be able to help you to migrate it across.

2020-12-16 13:32 UTC, enzonr commented
Oh no. Yury, can you help at some point?

I did not mean to do that!

On Wed, 16 Dec 2020, 14:14 Philip-Larsen-Donnelly, <notifications@github.com>
wrote:

> Note that the metadata stuff has also moved to a new repository since you
> forked this one 😬
> @YuryRog <https://github.com/YuryRog> may be able to help you to migrate
> it across.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dhis2/dhis2-docs/pull/515#issuecomment-746268555>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOOZOBH5X7GEPPXULZAHM4LSVCXEDANCNFSM4RR2AFXQ>
> .
>

2020-12-18 10:19 UTC, closed without merging