docs: Add missing files for the 2.33 sysadmin guide
dhis2/dhis2-docs pull request #529
Opened 2020-10-15 08:31 UTC by jaboto

The guide was missing some files.
Also added the SMS reporting one (related to Android App and the gateways that is already present in master and 2.34 -PR-)

2020-10-15 15:05 UTC, Philip-Larsen-Donnelly requested changes
Monitoring and Audit were introduced in 2.34

2020-10-15 15:05 UTC, Philip-Larsen-Donnelly commented on src/commonmark/en/content/sysadmin/audit.md
> +# Audit
I don't think this audit service is applicable to 2.33.

2020-10-15 15:05 UTC, Philip-Larsen-Donnelly commented on src/commonmark/en/content/sysadmin/monitoring.md
> +# Monitoring
I don't think the monitoring service is applicable to 2.33

2020-10-15 15:05 UTC, Philip-Larsen-Donnelly commented on src/commonmark/en/dhis2_system_administration_guide_INDEX.md
> +!INCLUDE "content/sysadmin/monitoring.md"
monitoring not applicable to 2.33

2020-10-15 15:05 UTC, Philip-Larsen-Donnelly commented on src/commonmark/en/dhis2_system_administration_guide_INDEX.md
> +!INCLUDE "content/sysadmin/audit.md"
audit not applicable to 2.33

2020-10-19 08:57 UTC, jaboto commented
Sorry about that. I copied the file from the other branch... Fixed now

2020-10-19 11:12 UTC, merged