docs: metadata endpoint to retrieve categoryOption/orgUnits association (DHIS2-4417)
dhis2/dhis2-docs pull request #732
Opened 2021-06-02 14:16 UTC by gnespolino

2021-06-03 05:54 UTC, stian-sandvold requested changes

2021-06-03 05:54 UTC, stian-sandvold commented on developer/web-api/metadata.md
> +This endpoint is the preferred way to retrieve program org unit associations.
Try to be consistent when referring to the different entities:
CategoryOption / Organisation Units -> OrganisationUnits
program org unit associations -> retrieve associations between Program and OrganisationUnits.

2021-06-03 05:54 UTC, stian-sandvold commented on developer/web-api/metadata.md
> +CategoryOptions that are accessible by all orgUnits are returned with an empty array (`[]`) of orgUnits.
orgUnits -> OrganisationUnits

2021-06-03 05:54 UTC, stian-sandvold commented on developer/web-api/metadata.md
> +Programs that are accessible by all orgUnits are returned with an empty array (`[]`) of orgUnits.
OrganisationUnits

2021-06-08 12:12 UTC, larshelge approved these changes

2021-06-08 12:13 UTC, merged