DHIS2-11044_ErrorWidget
dhis2/dhis2-docs pull request #773
Opened 2021-07-07 09:40 UTC by EirikHaugstulen

Added documentation of the error widget in the enrollment overview.

2021-07-09 12:46 UTC, karolinelien commented
LGTM 👍

2021-07-09 12:47 UTC, karolinelien approved these changes

2021-07-09 12:56 UTC, simonadomnisoru approved these changes

2021-07-09 13:14 UTC, huocha commented on src/user/using-the-capture-app.md
> +The error widget will display errors recieved from configured program rules which are not associated with a specific data element or attribute.
NIT: typo here: `received`

2021-07-12 07:22 UTC, cooper-joe requested changes

2021-07-12 07:22 UTC, cooper-joe commented on src/user/using-the-capture-app.md
> +On the enrollment dashboard, you can view the Error widget.
I suggest removing this line and building into the sentence below.

2021-07-12 07:22 UTC, cooper-joe commented on src/user/using-the-capture-app.md
> +The error widget will display errors recieved from configured program rules which are not associated with a specific data element or attribute.
I suggest simplifying and removing references to the DHIS2 data model:
`On the enrollment dashboard, the errors widget displays errors related to the current dashboard. The widget shows errors that are not associated with any specific data item.`

2021-07-12 07:22 UTC, cooper-joe commented on src/user/using-the-capture-app.md
> +If there are no errors, the error widget will not be displayed.
I suggest rewording the _will not be displayed_ to a simpler _is hidden_:
`If there aren't any errors to show for the current dashboard then the widget is hidden.`

2021-07-12 09:38 UTC, EirikHaugstulen commented
Thanks @cooper-joe & @huocha! 
Implemented the changes 👍

2021-07-13 11:49 UTC, cooper-joe approved these changes

2021-08-18 07:45 UTC, merged