DHIS2-11045_WarningWidget
dhis2/dhis2-docs pull request #774
Opened 2021-07-07 10:01 UTC by EirikHaugstulen

Added documentation on the Warning widget in the enrollment overview.

2021-07-09 12:48 UTC, karolinelien approved these changes
LGTM 👍

2021-07-09 12:56 UTC, simonadomnisoru approved these changes

2021-07-09 13:15 UTC, huocha commented on src/user/using-the-capture-app.md
> +The warning widget will display warnings recieved from configured program rules which are not associated with a specific data element or attribute.
NIT: typo `received`

2021-07-12 07:17 UTC, cooper-joe requested changes

2021-07-12 07:17 UTC, cooper-joe commented on src/user/using-the-capture-app.md
> +On the enrollment dashboard, the warning widget will be displayed.
I suggest removing this line and incorporating it into the sentence below, see next suggestion.

2021-07-12 07:17 UTC, cooper-joe commented on src/user/using-the-capture-app.md
> +The warning widget will display warnings recieved from configured program rules which are not associated with a specific data element or attribute.
I suggest simplifying and adding in the previous line:
`On the enrollment dashboard, the warning widget displays warnings related to the current dashboard. The widget shows warnings that are not associated with any specific data item.`

This is user documentation, so we should, as I understand it, avoid referring to the DHIS2 data model.

2021-07-12 07:17 UTC, cooper-joe commented on src/user/using-the-capture-app.md
> +If there are no warnings, the warning widget will not be displayed.
I suggest rewording:
`If there aren't any warnings to show for the current dashboard then the widget is hidden.`

2021-07-12 09:41 UTC, EirikHaugstulen commented
Thanks!
Implemented the changes!

2021-07-13 11:48 UTC, cooper-joe approved these changes

2021-08-18 07:47 UTC, merged