DHIS2-10981_FeedbackWidget
dhis2/dhis2-docs pull request #776
Opened 2021-07-07 11:32 UTC by EirikHaugstulen

Added documentation on the Feedback widget in the enrollment overview.

2021-07-09 13:10 UTC, karolinelien approved these changes
LGTM 👍

2021-07-09 13:16 UTC, huocha approved these changes

2021-07-12 07:12 UTC, cooper-joe requested changes

2021-07-12 07:12 UTC, cooper-joe commented on src/user/using-the-capture-app.md
> +If there are no feedback for the specific context, the widget will display a text to inform that there are no feedbacks.
I suggest simplifying this sentence to:
`If there isn't any feedback for the current dashboard, the widget shows a short _empty_ message.`

2021-07-12 07:12 UTC, cooper-joe commented on src/user/using-the-capture-app.md
> +If there are no program rules that could potentially lead to a displayed feedback, the widget will be removed completely.
I suggest simplifying to:
`If there aren't any program rules that could show feedback for the current dashboard then the widget is hidden.`

2021-07-12 07:20 UTC, cooper-joe requested changes

2021-07-12 07:20 UTC, cooper-joe commented on src/user/using-the-capture-app.md
> +On the enrollment dashboard, you can view the Feedback widget.
I suggest removing this line and adding into the sentence below, see suggestion.

2021-07-12 07:20 UTC, cooper-joe commented on src/user/using-the-capture-app.md
> +The feedback widget displays text and key/value-pairs that are triggered by program rules and are not specific to any data element or attribute.
I suggest simplifying and removing references to the DHIS2 data model:

`On the enrollment dashboard, the feedback widget displays text and values that are triggered by certain conditions. If the current dashboard triggers some rules set up in the program, the text or values will be automatically displayed.`

2021-07-12 10:03 UTC, EirikHaugstulen commented
Thanks for the feedback! 
Implemented the changes 👍

2021-07-13 11:47 UTC, cooper-joe approved these changes

2021-07-14 08:54 UTC, simonadomnisoru approved these changes

2021-08-18 08:02 UTC, merged